### ISSUE TITLE
Can you clarify how to use this?

### ISSUE THREAD

**Issue by ShatReal** [uberfig/godot-build-and-deploy-plugin#1]
I have created an .export folder and placed my folders in there. I have also set the game name and all of the other fields. But nothing seems to happen when I click "build" and then "push to itch"?

**Comment by uberfig** [comment]
Sorry this process is not as simple as it should be, I will try to address in I future updates. When I get home tonight I'll make a setup and demo video and hopefully it will help
- [ ] Make video
- [ ] Upload to YouTube 
- [ ] Attach to the itch page

**Comment by uberfig** [comment]
Do you have butler installed (and added to path if on windows)?

**Comment by ShatReal** [comment]
Yes, I do

**Comment by uberfig** [comment]
Could you please send me a screenshot of the build menu

**Comment by uberfig** [comment]
I tried running the plugin and now it isn't working :(
I'll get back to you when I figure it out

**Comment by uberfig** [comment]
I just realised that the export all button exists 😢 
I guess the build menu is useless

**Comment by uberfig** [comment]
I'm not sure why the build menu isn't working but the deploy menu is working as intended

**Comment by uberfig** [comment]
I'm going to depreciate the build menu. If I can fix it in the future I will bring it back, but for now I'm going to remove it as it does the same thing as the export menu, but worse

However the deploy portion of the project is working perfectly and I will get to work on the tutorial

**Comment by ShatReal** [comment]
Alright, thanks for answering!

**Comment by uberfig** [comment]
no problem!

**Comment by uberfig** [comment]
I have commented out the build menu and I am going to put usage instructions in an about menu. I may also put together a menu that could prep a folder for deployment

**Comment by uberfig** [comment]
I have finished the tutorial and changed up the menu to me more responsive!
