### ISSUE TITLE
Deploy buttons do nothing on macOS

### ISSUE THREAD

**Issue by terijaki** [uberfig/godot-build-and-deploy-plugin#5]
I am running Godot 3.4.3 stable on macOS 12.2.1 and nether **Login to Butler** nor **Push to Itch** have any effect.

It seems to be related to https://github.com/godotengine/godot/issues/55379

(running butler manually in the Terminal works fine)

**Comment by uberfig** [comment]
What version of the plugin are you using? If you are using 1.5 have you tried the butler off path feature?

**Comment by terijaki** [comment]
One Click Build and Deploy 1.5

I didn't notice the fourth tab at first...

Yes, with butler off path it worked and I was able to push to itch successfully.

(when using Terminal though simply typing "butler" works fine for me. e.g. the path is configured correctly)

I was expecting the terminal window to pop up though, or to receive any kind of confirmation. I got nothing other than seeing that Godot was busy. Is this intended?

**Comment by uberfig** [comment]
I'm happy to hear that the off path feature was able to fix the problem! I don't have very much experience with macOS so I'm not certain of the root of the problem. At the moment, there isn't really any prompt to let you know the builds were uploaded successfully, but I will look into this and I might add a pop-up to let you know when it's finished in future versions. If you want to prevent godot from becoming busy while uploading, you can turn off pause mode but I wouldn't recommend it.
