### ISSUE TITLE
Does not connect to Butler (ERR_CANT_FORK)

### ISSUE THREAD

**Issue by cybernaut4** [uberfig/godot-build-and-deploy-plugin#7]
I tried to login with Butler and got this error: 

platform/windows/os_windows.cpp:2873 - Condition "ret == 0" is true. Returned: ERR_CANT_FORK

I tried filling the form with gibberish but I got the same error.

Game has its **privacy set to restricted**. Could this have to do with it?

**Comment by uberfig** [comment]
I'm not sure what the source of the error is, I am assuming this is an issue with butler and not the plugin. I will try my best to replicate your issue and see if I can find a solution

**Comment by uberfig** [comment]
I think I have found the cause of your error, Do you have butler installed and added to path?
